apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: adt-eval
description: main application pipeline
serialPipeline:
 stages:
 - targetId: run-qsdev
   profiles: [dev]
 - targetId: run-qsprod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-qsdev
description: Cloud Run development service
run:
 location: projects/adt-eval/locations/us-east1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-qsprod
description: Cloud Run production service
run:
 location: projects/adt-eval/locations/us-east1